### ISSUE TITLE
[Test plan] Hub & cluster

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1135]
### Hub

- [x] Install Hub in CLI mode.
  - [x] Verify can configure [OIDC connector](https://gravitational.com/gravity/docs/ver/6.x/config/#example-google-oidc-connector), for example:
```yaml
kind: oidc
version: v2
metadata:
  name: google
spec:
  redirect_url: "https://<hub-advertise-addr>/portalapi/v1/oidc/callback"
  client_id: <cliend-id>
  client_secret: <client-secret>
  issuer_url: https://accounts.google.com
  scope: [email]
  claims_to_roles:
    - {claim: "hd", value: "gravitational.com", roles: ["@teleadmin"]}
```
  - [x] Verify can log into the Hub UI.
  - [x] Verify can update TLS certificate via [resource](https://gravitational.com/gravity/docs/ver/6.x/config/#tls-key-pair) or UI.
  - [x] Verify can log in with `tsh login --proxy=<hub>`.
  - [x] Verify can push Telekube cluster image into the Hub.
  - [x] Verify can invite user to the Hub using CLI.
    - [x] Create a user invite: `gravity users add test@example.com --roles=@teleadmin`.
    - [x] Open the generated link and signup.
    - [x] Verify can login with the created user.
  - [x] Verify can reset the Hub user password using CLI.
    - [x] Request a user reset: `gravity users reset test@example.com`.
    - [x] Open the generated link and reset the password.
    - [x] Verify can login with the new password.

#### With Cluster Image Downloaded From The Hub

- [x] Install Telekube cluster image using installer downloaded from the Hub: CLI or UI.
  - [x] Verify cluster connects back to the Hub after installation.
    - [x] Verify remote support is configured but turned off: cluster appears "offline" in the Hub.

### Hub / Cluster Upgrade & Connectivity

- [x] Install a Hub of the previous LTS version.
  - [x] Push Telekube app of the previous LTS version into it.
  - [x] Install a single-node Telekube cluster and connect it to the Hub.
- [x] Upgrade the Hub to the current version.
  - [x] Verify the cluster stays connected & online.
- [x] Upgrade the cluster to the current version.
  - [x] Verify the cluster stays connected & online.
