### ISSUE TITLE
[Test plan] Persistent storage

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1155]
### Setup

- [x] Install a cluster with OpenEBS enabled (e.g. `telekube` application).
  - [x] Make sure the node contains at least 2 block devices that can be used by OpenEBS.
  - [x] Optionally configure OpenEBS-discovered devices like described in the [docs](https://gravitational.com/gravity/docs/storage/#configure-openebs), for example:

```yaml
# storage.yaml
kind: PersistentStorage
version: v1
spec:
  openebs:
    filters:
      devices:
        exclude: ["/dev/sda", "/dev/sdb", "/dev/sdc"]
```
```bash
$ gravity resource create storage.yaml
```

  - [x] Verify OpenEBS discovered proper devices: `kubectl get blockdevices -A`.

### Local provisioner, host path

- [x] Create a persistent volume claim for hostpath volume and a pod like in the example below.
  - [x] Make sure the PVC/PV have been created and `nginx-hostpath` pod is running: `kubectl get pv,pvc,pods`.

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-hostpath
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: local-vol
      mountPath: /data
  volumes:
  - name: local-vol
    persistentVolumeClaim:
      claimName: claim-hostpath
```

### Local provisioner, block device

- [x] Create a persistent volume claim for block device volume and a pod like in the example below.
  - [x] Make sure the PVC/PV have been created and `nginx-device` pod is running: `kubectl get pv,pvc,pods`.

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-device
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-device
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-device
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: local-vol
      mountPath: /data
  volumes:
  - name: local-vol
    persistentVolumeClaim:
      claimName: claim-device
```

### cStor

**Note, this test requires iscsid running on host.**

- [x] Create storage pool claim, storage class, persistent volume claim and pod like in the example below.
  - [x] Make sure the PVC/PV have been created and `nginx-cstor` pod is running: `kubectl get pv,pvc,pods`.

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-cstor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-cstor
apiVersion: v1
kind: Pod
metadata:
  name: nginx-cstor
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: local-vol
      mountPath: /data
  volumes:
  - name: local-vol
    persistentVolumeClaim:
      claimName: claim-cstor
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-pool"
      - name: ReplicaCount
        value: "1"
provisioner: openebs.io/provisioner-iscsi
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-pool
spec:
  name: cstor-pool
  type: disk
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList:
    # PUT YOUR BLOCK DEVICE ID HERE
    - blockdevice-b050316406c81f24d27dd8de22ae3164
```
