### ISSUE TITLE
Add ability to bundle gravity resources with installer

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1382]
Gravity resources can be created in the cluster during installation by providing a --config parameter to the command:

```
gravity install --config=<resources.yaml>
```

There is no ability, though, to package some resources with the installer built with tele build and have gravity create them automatically in the cluster without having to provide the --config flag.

Examples of when this may be useful:

* Include some tweaked cluster configuration via ClusterConfiguration resource i.e. to enable additional apiserver/kubelet/etc. flags.
* Include some other preconfigured things, e.g. bootstrap users/roles automatically, etc.

**Comment by mmellin** [comment]
This modifications would be really useful.  Currently we modify a couple runtime environment parameters and it would be very useful to have this bundled during the installation time instead of relying on the user, or our automation tool, to create this after the fact.

What we include today within the file referenced with `--config`:
```yaml
kind: RuntimeEnvironment
version: v1
spec:
  data:
    KUBE_PROXY_FLAGS: "--proxy-mode=ipvs"
    KUBE_COMPONENT_FLAGS: "--feature-gates=ServerSideApply=false"
```
