### ISSUE TITLE
[Enhancement] Extend user.yaml to accept hashed password

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#1501]
Currently Gravity encrypts the password with bcrypt prior to being saved. 

Customer use case is they have a super admin user, and would like to sync the password of super admin user to teleadmin. They only have the salt, not the actual password.

For example would like the following during user creation:

```
kind: user
version: v2
metadata:
  name: "admin@example.com"
spec:
  type: "admin"
  password: "$6$eDwm2y7tc/vbnrm8$hExym2EuxmhWzvcoTIpLHko89j...."
  roles: ["@teleadmin"]
```
