### ISSUE TITLE
[BUG] User Signup uses IP instead of public address

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/gravity#1502]
**Describe the bug**
Even if a public address is set (gravity.example.com) the signup url presented uses the local IP of a master node.

**To Reproduce**
Install a gravity cluster.  Add a auth gateway configuration with a domain:
```yaml
kind: authgateway
version: v1
spec:
  # Connection throttling settings
  connection_limits:
    # Max number of simultaneous connections
    max_connections: 1000
    # Max number of simultaneously connected users
    max_users: 250
  # Cluster authentication preferences
  authentication:
    # Auth type, can be "local", "oidc", "saml" or "github"
    type: oidc
    # Second factor auth type, can be "off", "otp" or "u2f"
    second_factor: otp
    # Default auth connector name
    connector_name: auth0
  # Determines if SSH sessions to Cluster nodes are forcefully terminated
  # after no activity from a client, for example "30m", "1h", "1h30m"
  client_idle_timeout: never
  # Determines if the clients will be forcefully disconnected when their
  # certificates expire in the middle of an active SSH session
  disconnect_expired_cert: false
  # DNS name that applies to all SSH, Kubernetes and web proxy endpoints
  public_addr:
    - example.gravitational.co:32009
```
If the below is set you still get the output below.  That could be a private IP that is not externally available to the user and requires them to change it.

$ sudo gravity users add --roles=@teleadmin steven
Signup token has been created and is valid for 8h0m0s hours. Share this URL with the user:
https://10.333.0.16:3009/web/newuser/8c5c9e0c6f485279b5bfe21e5b15af7d7be0893ccc9a8081eeaf446e3cd3s750

**Expected behavior**

The signup url uses the public address instead of the IP in the URL.

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: Ubuntu 18
 - Gravity [e.g. 5.5.4]:7.0.4
 - Platform [e.g. Vmware, AWS]: GCP
