### ISSUE TITLE
[BUG] Teleport nodes can't connect after replacing all masters

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1515]
**Describe the bug**

When generating configuration for Teleport nodes, we put IPs of master nodes as auth servers there:

```yaml
teleport:
  auth_servers:
  - 127.0.0.1:3025
  - 10.128.0.16:3025
```

If all master nodes are replaced, workers won't be able to connect back anymore.

**To Reproduce**

**Expected behavior**

**Logs**

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]:
 - Platform [e.g. Vmware, AWS]:

**Additional context**
