### ISSUE TITLE
Setup better default kube-apiserver audit log policy

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1661]
**Describe the bug**

Currently, the kube-apiserver audit log policy is configured like this:

```
node-1:/$ cat /etc/kubernetes/audit-policy.yaml
apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
  # Log all Kubernetes Event objects at Request level
  - level: Request
    resources:
    - resources: ["events"]

  # As a fallback/default, log nothing at all
  - level: None
```

It only logs the Event-related events that makes it impossible to use this audit log for anything useful.

We need to have a better default, for example to log all Metadata requests for objects.

**To Reproduce**

**Expected behavior**

**Logs**

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]: 7.0
 - Platform [e.g. Vmware, AWS]:

**Additional context**
