### ISSUE TITLE
Cannot create a read-only role

### ISSUE THREAD

**Issue by gminog** [gravitational/gravity#1706]
I've been trying to create a read-only role for the Cluster web UI so that I can assign it to one or more users.
Those users should not be able to change/delete anything when it comes to the cluster.

Below you may find the role description (which is actually an enhancement of the @teleadmin role:
```
kind: role
metadata:
  name: read-only
spec:
  allow:
    kubernetes_groups:
    - admin
    logins:
    - root
    node_labels:
      '*': '*'
    rules:
    - resources:
      - role
      verbs:
      - list
      - read
    - resources:
      - auth_connector
      verbs:
      - list
      - read
    - resources:
      - session
      verbs:
      - list
      - read
    - resources:
      - trusted_cluster
      verbs:
      - list
      - read
  deny: {}
  options:
    cert_format: standard
    client_idle_timeout: 0s
    disconnect_expired_cert: false
    forward_agent: false
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```
Nevertheless, while trying to login using that role, I'm getting the following error:
```access denied to perform action "read" on "cluster"```

Note that the Gravity cluster version is 5.5.47.
Any ideas how to tackle this?
