### ISSUE TITLE
[BUG] Upgrade fails if new volume specifies uid without gid

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1788]
**Describe the bug**

If there's a volume specification in the manifest like this:

```yaml
  nodeProfiles:
    requirements:  
      volumes:
        - name: data
          path: /opt/data
          targetPath: /var/lib/data
          createIfMissing: true
          uid: 2020
```

The upgrade fails on the bootstrap phase with the following error:

```
User Message: failed to execute phase &#34;/bootstrap&#34;
        failed to run {[chown 2020: /opt/data] setting ownership of /opt/data to 2020: false}:
                exit status 1]
```

**To Reproduce**

**Expected behavior**

**Logs**

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]: 5.5+
 - Platform [e.g. Vmware, AWS]:

**Additional context**
