### ISSUE TITLE
[Test Plan 7.0 LTS] Web UI

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1833]
# Web UI

#### Side Nav
- [x] Verify that company logo is shown with a product version.
- [x] Verify that Gravity logo is shown when company logo is missing.

#### Top Nav
- [x] Verify that status indicator reflects these cluster states: healthy/processing/failed.
- [x] Verify that cluster public URL is shown.
- [x] Verify that "Info View" button opens "Cluster Information" dialog.

  Cluster Information
  - [x] Verify that public URL, internal URLs, and login command are shown.
  - [x] Verify that "copy" button copies the text to the clipboard.

- [x] Verify that user menu has "Logout" and "Account" options for local use.
- [ ] Verify that user menu has only "Logout" option for SSO user.

#### Dashboard
- [x] Verify that "CPU Usage" shows current CPU data.
- [x] Verify that "RAM Usage" shows current RAM data.
- [x] Verify that "Usage Over Time" shows the last 60 seconds of CPU/RAM data.
- [x] Verify that all charts show real-time data. You can open a terminal and try running `ls -R /` for a while.
- [x] Verify that "Audit Logs" table shows recent events (today).
- [x] Verify that "Operation" table shows cluster operations.

  Start a terminal session
  - [x] Verify that terminal session appears in the "Operation" table.

- [x] Verify that Application table shows all installed applications.

#### Nodes
- [x] Verify that "Nodes" table shows all joined nodes.
- [x] Verify that login dropdown shows a list of available logins.
- [x] Verify that clicking on the login opens a terminal.
- [x] Verify that "Add Node" button opens a dialog with instructions.
- [x] Verify that "Add Node" dialog shows valid instructions per selected role.

#### Terminal Session
- [x] Verify that input/output works as expected by typing on the keyboard.
- [x] Verify that window resize works (use `yum -y install mc` to install midnight commander)

  SCP
  - [x] Verify that Upload works.
  - [x] Verify that Upload handles invalid paths and network errors.
  - [x] Verify that Download works.
  - [x] Verify that Download handles invalid paths and network errors.

#### Logs
- [x] Verify that Logs are shown.

  Log forwarder settings
  - [x] Verify that Creating/Deleting/Editing a log forwarder works.

#### Audit Logs
- [x] Verify that Audit events of different types are shown.
- [x] Verify that "Details" button opens a dialog with JSON.
- [x] Verify that "Today" and "7 Days" options correctly filter events.
- [x] Verify that "Custom" option opens a date picker dialog.

#### Roles
- [x] Verify that roles are shown.
- [x] Verify that "Create New Role" dialog works.
- [x] Verify that deleting and editing a role works.
- [x] Verify that error is displayed when saving invalid input.

#### Users
- [x] Verify that users are shown.
- [x] Verify that creating a new user works.
- [x] Verify that editing user roles works.
- [x] Verify that removing a user works.

  Reset Password
  - [x] Verify that "Reset Password" dialog shows a reset link.

  Invite User
  - [x] Verify that role dropdown shows all existing roles.
  - [x] Verify that clicking on "Create invite link" shows an invite URL.

#### Auth Connectors
- [ ] Verify that creating OIDC/SAML/GITHUB connectors works.
- [ ] Verify that editing  OIDC/SAML/GITHUB connectors works.

  Templates
  - [x] Verify that "New OIDC connector" dialog has OIDC template.
  - [x] Verify that "New SAML connector" dialog has SAML template.
  - [x] Verify that "New SAML connector" dialog has GITHUB template.

  Card Icons
  - [x] Verify that GITHUB card has github icon
  - [x] Verify that SAML card has SAML icon
  - [x] Verify that OIDC card has OIDC icon

#### HTTPS Certificate
- [x] Verify that it shows certificate details.
- [x] Verify that updating a certificate works (try submitting invalid file formats).

#### Kubernetes
- [x] Verify namespace selector.

  Config maps
  - [x] Verify that configs maps are shown.
  - [x] Verify that editing config maps with multiple files works. Should see multiple tabs and "unsaved" changes indicator.

  Pods
  - [x] Verify that pods of different statuses are correctly displayed. Failed should be in red.
  - [x] Verify that string search on table columns works.

    Container menu
    - [x] Verify that "View Logs" works.
    - [x] Verify that SSH to container works.

    Action menu
    - [x] Verify that "Details" display the JSON dialog.
    - [x] Verify that "Monitoring" opens the monitoring screen with selected pod charts.
    - [x] Verify that "Logs" opens the logs screen with selected pod logs.

  Services
  - [x] Verify that services are displayed.
  - [x] Verify that "Details" opens a dialog with JSON.

  Jobs
  - [x] Verify that jobs are displayed.
  - [x] Verify that "Details" opens a dialog with JSON.

  Daemon Sets
  - [x] Verify that daemon sets are displayed.
  - [x] Verify that "Details" opens a dialog with JSON.

  Deployments
  - [x] Verify that deployments are displayed.
  - [x] Verify that "Details" opens a dialog with JSON.

#### Monitoring
- [x] Verify that Grafana charts work.

#### Account
- [x] Verify that changing a password works with 2FA disabled.
- [x] Verify that changing a password works with 2FA enabled.

#### License
  Make sure that Cluster has a license, then navigate to the license screen via top right corner menu (logout menu)
- [x] Verify that license details are displayed.
- [x] Verify that updating a license works.

#### Extensions
Set the following settings in the manifest file
```
app.manifest.extensions.monitoring.disabled: true
app.manifest.extensions.kubernetes.disabled: true
app.manifest.extensions.logs.disabled: true
```
 - [x] Verify that Kubernetes, Logs, and Monitoring features are hidden.

### Invite Form
- [x] Verify that company logo is shown.
- [x] Verify input validation.
- [x] Verify that invite works with 2FA disabled.
- [ ] Verify that invite works with OTP enabled.
- [ ] Verify that invite works with U2F enabled.
- [x] Verify that error message is shown if an invite is expired/invalid.

### Login Form
- [x] Verify that company logo is shown.
- [x] Verify input validation.
- [x] Verify that login works with 2FA disabled.
- [ ] Verify that login works with OTP enabled.
- [ ] Verify that login works with U2F enabled.
- [ ] Verify that SSO login works for Github/SAML/OIDC.
- [x] Verify that account is locked after several unsuccessful attempts.

#### Clusters
- [ ] Verify that 2 types of cluster cards (bundle and cluster) are shown.
- [x] Verify that empty indicator is shown when there are no clusters.

  Cluster Card
  - [ ] Verify that bundle card displays icons of installed application.
  - [ ] Verify that location indicator works (AWS or Onprem).
  - [ ] Verify that cluster labels are displayed.
  - [ ] Verify cluster status indicator (green/yellow/red).

#### Catalog
- [x] Verify that app images are displayed.
- [x] Verify that empty indicator is shown when there are no images.

  App Card
- [x] Verify that dropdown with versions works.
- [x] Verify that cluster image has the right icon.
- [x] Verify that bundle image has the right icon.
- [x] Verify install instructions for cluster and bundle images.
- [x] Verify that download button works.

#### Licenses
- [x] Verify that license generator works.
- [x] Verify input validation by entering invalid values.

#### User/Auth
  For Users, Roles, and Auth Connectors, please use Cluster steps to verify this functionality.

#### Settings
  For HTTP Cerifticate and for Account, please use Cluster steps to verify this functionality.

### Installer
  Create a cluster image which requires EULA, a valid License, and has Bandwagon step.
  Start an installer.

#### EULA
- [x] Verify that EULA agreement is shown asking a user to accept it.

#### Step. License
- [x] Verify that "License" step is shown.
- [x] Verify that step indicator has the correct number of steps (5).
- [x] Verify that error is shown when entering invalid license.

#### Step. Name You cluster
- [x] Verify that cluster name is required.

  Additional options
  - [x] Verify that input validation for subnet values works.
  - [x] Verify that creating cluster labels works.

#### Step. Capacity
- [x] Verify that profile selector works.
- [x] Verify that input fields for IP Address and Mounts work (check input validation).
- [x] Verify that "VERIFY" button works (should show a notification banner on top).

#### Step. Progress
- [x] Verify that progress indicator works.
- [x] Verify that installation logs work.
- [x] Verify that when installation fails, the error is shown with "DOWNLOAD TARBALL" button.

#### Step. Create Admin
- [x] Verify that creating an admin user works. After submitting a form, a user should be redirected to the cluster UI.

### RBAC
 Create the following role
```
  kind: role
  metadata:
    name: no_access
  spec:
    allow:
      kubernetes_groups:
      - admin
      logins:
      - root
      node_labels:
        '*': '*'
      rules:
      - resources:
        - cluster
        - role
        verbs:
        - read
    deny: {}
    options:
  version: v3
```
  - [x] Verify that a user has access only to: Nodes, Logs, Operations.
  - [x] Verify that Nodes screen does not display k8s labels.

#### Add Role `list` access.
```
    - resources:
      - role
      verbs:
      - read
```
  - [x] Verify that a list of roles is visible.
  - [x] Verify that changing/creating a role is not allowed.

#### Add Role `update` access.
```
    - resources:
      - role
      verbs:
      - update
```
  - [ ] Verify that changing/creating a role is allowed.

#### Add Event `list` access.
```
    - resources:
      - event
      verbs:
      - list
```
  - [x] Verify that list of events is displayed. In Event tab and on the Dashboard.

#### Add Log forwarder `list` access.
  ```
    - resources:
      - logforwarder
      verbs:
      - list
  ```
  - [x] Verify that a list of log forwarders is visible.
  - [x] Verify that changing/creating a log forwarder is not allowed.

#### Add Log forwarder `update` access.
```
    - resources:
      - logforwarder
      verbs:
      - update
```
  - [ ] Verify that changing/creating a log forwarder is allowed.

#### Add Auth Connector `list` access.
```
    - resources:
      - auth_connector
      verbs:
      - list
```
  - [x] Verify that a list of auth connectors is visible.
  - [x] Verify that changing/creating an auth connector is not allowed.

#### Add auth_connector `update` access.
```
    - resources:
      - auth_connector
      verbs:
      - update
```
  - [ ] Verify that changing/creating an auth connector is allowed.

#### Add app `list` access.
```
    - resources:
      - app
      verbs:
      - list
```
  - [x] Verify that list of apps is displayed in Gravity HUB.

#### Add Cluster `connect` access.
```
    - resources:
      - cluster
      verbs:
      - connect
```
  - [ ] Verify that K8s tab is displayed.
  - [ ] Verify that Nodes screen displays K8s labels.

**Comment by eldios** [comment]
the RBAC role is not working... had to use:
```
kind: role
metadata:
  # insert the name of your role here:
  name: test_manual
  
spec:
  # This example defines an administrative role. It maps to Kubernetes "admin"
  # group and allows SSH to every node.
  allow:
    # This role is mapped to Kuberntes 'admin' group.
    kubernetes_groups: [admin]

    # List of allowed SSH logins
    logins: [root]

    # List of node labels that users can SSH into
    node_labels:
      '*': '*'

    # RBAC rules for various resources within a cluster.
    rules:
    - resources: ['cluster','role']
      verbs: ['read']

  # The 'deny' section can have similar settings that override their 'allow' counterparts
  deny:
    logins: []

  options:
      # Limits user credentials to 8 hours. After the time to live (TTL) expires,
      # users must re-login
      max_session_ttl: 8h0m0s
  # the deny section uses the identical format as the 'allow' section.
  # the deny rules always override allow rules.
  deny: {}
version: v3
```
