### ISSUE TITLE
tsh allows access to all clusters even if role restricts

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/gravity#1891]
### Description

**What happened**:

A user has a role that allows for accessing the hubcluster and viewing cluster that have matching role labels.  The hub will restrict listing the clusters to those allowed to read. 

`tsh` will list all available clusters and all the user to ssh into any of the cluster nodes.

```yaml
    - resources:
      - 'cluster'
      verbs:
      - 'read'
      where: equals(resource.metadata.name, "hubcluster")
    - resources:
      - cluster
      verbs:
      - read
      - connect
      where: contains(user.spec.traits["roles"], resource.metadata.labels["env"])
```

**What you expected to happen**:

The same clusters listed in the hub are what are available in `tsh` the user should not able able to login to those clusters.

**How to reproduce it (as minimally and precisely as possible)**:

Install a hub with two connected clusters and configure with auth0 or another identity manager.  The clusters should have different labels (env:dev, env:staging).  The user's role will only allow for one such as dev.  Login via tsh and login to the hub.

### Environment

 - Gravity version [e.g. 7.0.11]: 7.0.13
 - OS [e.g. Redhat 7.4]: ubuntu
 - Platform [e.g. Vmware, AWS]: GCP
