### ISSUE TITLE
Provide a way to make gravity-site not a load balancer

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1931]
### Feature Request

The use-case is that a customer would like to prevent gravity-site service from creating a load balancer when deploying with cloud integration enabled.

In another scenario a customer wants to have more control over the service annotations e.g. to enable/disable internal load balancer.

### Proposed spec

Extend the existing [ClusterConfiguration](https://gravitational.com/gravity/docs/config/#general-cluster-configuration) resource with the gravityController section that allows to control certain parts of gravity-site service:

```yaml
kind: ClusterConfiguration
version: v1
spec:
  # global and kubelet are existing fields
  global:
  kubelet:
  # new field
  gravityControllerService:
    type: NodePort
    annotations:
      "cloud.google.com/load-balancer-type": "Internal"
```

* The "type" field should allow only `NodePort` or `LoadBalancer` (`ClusterIP` will break internal gravity stuff).
* Default values should be taken from the current gravity-site service:
  * "type" should be `LoadBalancer`.
  * "annotations" should contain two AWS-specific annotations (see service definition linked below).

### Behavior

- [ ] When this resource (with gravityControllerService section) is provided during install (via `--config` flag), gravity-site service should be created with those settings applied.
- [ ] If this resource (with gravityControllerService) is created/updated when the cluster is deployed, it should update gravity-site service accordingly (same as if it was updated using kubectl, no operation needed).
- [ ] During upgrade, these settings should also be considered and applied to the updated gravity-site service.

### Implementation details

The gravity-site service is currently statically defined among site-app resources here:

https://github.com/gravitational/gravity/blob/version/7.0.x/assets/site-app/resources/site.yaml#L276-L293

The change proposed in this ticket means that the service will now have to be created dynamically by install procedure and updated during an upgrade.
