### ISSUE TITLE
Bug: Planet: Wildcard mounts don't understand directories

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#2260]
### Description

**What happened**:
Reported by OSS user in Gravity Community Slack. Basically, with nvidia drivers 450 (nvidia-driver-450), a /dev subdirectory is created with two  caps devices. Our device mounting code in planet doesn't support if the detected mount is a directory.

The hiearchy looks something like:
```
/dev/nvidia-modeset
/dev/nvidia-uvm
/dev/nvidia-uvm-tools
/dev/nvidia0
/dev/nvidiactl

/dev/nvidia-caps/nvidia-cap1
/dev/nvidia-caps/nvidia-cap2
```

Error:
```
rootfs/usr/bin/planet[16521]: WARN             Failed to run. error:[
ERROR REPORT:
Original Error: *trace.BadParameterError unsupported device type: "/dev/nvidia-caps"
Stack Trace:
/gopath/src/github.com/gravitational/planet/lib/box/srv.go:455 github.com/gravitational/planet/lib/box.getDeviceInfo
/gopath/src/github.com/gravitational/planet/lib/box/srv.go:428 github.com/gravitational/planet/lib/box.convertToDevices
/gopath/src/github.com/gravitational/planet/lib/box/srv.go:411 github.com/gravitational/planet/lib/box.getLibcontainerConfig
/gopath/src/github.com/gravitational/planet/lib/box/srv.go:149 github.com/gravitational/planet/lib/box.Start
/gopath/src/github.com/gravitational/planet/tool/planet/start.go:290 main.start
/gopath/src/github.com/gravitational/planet/tool/planet/start.go:68 main.startAndWait
/gopath/src/github.com/gravitational/planet/tool/planet/main.go:439 main.run
/gopath/src/github.com/gravitational/planet/tool/planet/main.go:61 main.main
/opt/go/src/runtime/proc.go:200 runtime.main
/opt/go/src/runtime/asm_amd64.s:1337 runtime.goexit
User Message: unsupported device type: "/dev/nvidia-caps"
] planet/main.go:737
Oct 20 03:20:05 anv-alien gravity[16521]: [ERROR]: unsupported device type: "/dev/nvidia-caps"
```

app.yaml:
```
 # This setting makes sure specified devices from host are made available
      # inside Gravity container
      devices:
        # Device(-s) path, treated as a glob
        - path: /dev/nvidia*
          # Device permissions as a composition of 'r' (read), 'w' (write) and
          # 'm' (mknod), default is 'rw'
          permissions: rw
          # Device file mode in octal form, default is '0666'
          fileMode: "0666"
          # Device user ID, default is '0'
          uid: 0
          # Device group ID, default is '0'
          gid: 0
```

Sources: https://github.com/gravitational/planet/blob/version/6.3.x/lib/box/srv.go#L447-L456

**What you expected to happen**:
The devices to be properly mounted.

**How to reproduce it (as minimally and precisely as possible)**:

### Environment

 - Gravity version [e.g. 7.0.11]: Reported on 6.3.7 (Out of Support), but likely occurs on other versions.
