### ISSUE TITLE
Teleport with Kubernetes integration not working

### ISSUE THREAD

**Issue by sandromello** [gravitational/gravity#248]
I've tested Teleport Kubernetes integration functionality and isn't working properly because the kube-controller-manager doesn't have `--cluster-signing-cert-file` and `--cluster-signing-key-file` set.

When teleport tries to create a CSR nothing happens because the controller manager doesn't generate any certificate. I've modified the `kube-controller-manager` systemd unit passing those flags and it works.

Teleport Version: `Teleport v3.1.4 git:v3.1.4-0-g9b7b5b8b go1.11.4`

```yaml
# /etc/teleport.yaml
auth_service:
  kubeconfig_file: /etc/kubeconfig.test
  cluster_name: main
  authentication:
    second_factor: off
  public_addr: public_addr:3025
proxy_service:
  public_addr: public_addr:3080
  ssh_public_addr: public_addr:3023
  kubernetes:
    enabled: yes
    public_addr: ['public_addr:3026']
```

Started teleport with: `./teleport start --insecure -d`

Then, with `tsh`:

```bash
tsh --proxy=public_addr --insecure login --user san
# it hangs because teleport timed out waiting for a certificate from CSR API
kubectl get pod
```

> `--insecure` was used for testing purporses

Gravity Version:

```
Edition:	open-source
Version:	5.4.4
Git Commit:	7307d06d7aa775276cf9097aeade96d4dfac1e2
```

References:
- https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#access-to-key-and-certificate
- https://gravitational.com/teleport/docs/admin-guide/#kubernetes-integration
