### ISSUE TITLE
Cannot build app tarballs in a docker container

### ISSUE THREAD

**Issue by gotwarlost** [gravitational/gravity#286]
We have an app that builds fine on a pristine machine with docker installed. Our build system, however, runs the same commands in a docker container (we use gravitational/debian-grande for this build) mounting the docker socket from the host.

The `tele build` command is able to download images from our internal docker repos just fine but is unable to create the local registry and register images there. This is what happens:

```
	Still embedding application container images (4 minutes elapsed)
time="2019-02-26T05:44:05Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." source=local-docker-registry
* [3/6] Build aborted after 6 minutes 
[ERROR]: failed to push images to local registry

```

Any pointers on how we could fix this issue or what the root cause might be? Thanks!

**Comment by klizhentas** [comment]
Check out this doc and see if it helps:

https://gravitational.com/gravity/docs/pack/#building-with-docker

**Comment by gotwarlost** [comment]
Thanks for that link. I'm pretty much doing everything in there _except_ for running the container with host networking which I suspect makes all the difference.

**Comment by gotwarlost** [comment]
yup. that was it. Thanks!

**Comment by robertoyoc** [comment]
Hey @gotwarlost could you please share your solution? I'm facing the same problem.

```
 	Still embedding application container images (1 minute elapsed)
 time="2020-11-05T16:41:09Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." source=local-docker-registry
 Thu Nov  5 16:41:09 UTC	Build finished in 6 minutes 
 [ERROR]: failed to push images to local registry
 	Get http://127.0.0.1:39925/v2/: dial tcp 127.0.0.1:39925: connect: connection refused
```



This is my current conf:
```
image: private-registry/gravity-builder
stages:
    - build
    - copy
    - install

build image:
    stage: build
    services:
        - docker:19.03.12-dind
    variables:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_TLS_CERTDIR: ""
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - tele build -o Hub.tar hub/resources/app.yaml
    artifacts:
        paths:
            - Hub.tar

```
