### ISSUE TITLE
[BUG] Cannot overwrite $KUBE_COMPONENT_FLAGS variable with `--config=envars.yml` option

### ISSUE THREAD

**Issue by mmellin** [gravitational/gravity#655]
**Describe the bug**

Providing a file to the `--config` option during `./gravity install` updates the runtime environmental variables in Planet.  These variables seem to be stored in `/etc/container-environment` within Planet.  

All variables I've tried seem to allow overwriting with the except of $KUBE_COMPONENT_FLAGS.  The behavior for this variable seems additive whereby whatever is in my `envars.yml` file is added to whatever the defaults are.

Example:

```
node01:/$ cat /etc/container-environment
KUBE_ENABLE_IPAM="true"   << overwritten
KUBE_PROXY_FLAGS="--proxy-mode=ipvs"    << overwritten
KUBE_COMPONENT_FLAGS="--feature-gates=AllAlpha=true,APIResponseCompression=false,BoundServiceAccountTokenVolume=false,CSIDriverRegistry=false,CSINodeInfo=false,KubeletPodResources=false,ServerSideApply=false --feature-gates=AllAlpha=true,APIResponseCompression=false,BoundServiceAccountTokenVolume=false,CSIDriverRegistry=false,CSINodeInfo=false,KubeletPodResources=false"  << FAILED to overwrite
```

Perhaps this a protection mechanism, but I would like to modify these flags and, at a minimum, disable the `ServerSideApply` feature gate.

**To Reproduce**

Create an `envars.yaml` file:

```
kind: RuntimeEnvironment
version: v1
spec:
  data:
    KUBE_COMPONENT_FLAGS: "--feature-gates=AllAlpha=true,APIResponseCompression=false,BoundServiceAccountTokenVolume=false,CSIDriverRegistry=false,CSINodeInfo=false,KubeletPodResources=false,ServerSideApply=false"
```
Using Gravity 6.1.4 and Planet 6.1.3-11503, issue the command `./gravity install --config=envars.yaml`

**Expected behavior**

Output of `/etc/container-environment` would show the KUBE_COMPONENT_FLAGS env variabe as identical to the `envars.yaml` file.

**Logs**

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: Centos7
 - Gravity [e.g. 5.5.4]: 6.1.4
 - Platform [e.g. Vmware, AWS]: Vmware

**Additional context**

**Comment by a-palchikov** [comment]
You're correct - the `KUBE_COMPONENT_FLAGS` environment variable is synthesized automatically. The 
[ClusterConfiguration](https://gravitational.com/gravity/docs/config/#general-cluster-configuration) resource is a way to configure the feature gates.

**Comment by wadells** [comment]
Looks similar to https://github.com/gravitational/gravity/issues/544, which also wants to munge `KUBE_COMPONENT_FLAGS`.

**Comment by wadells** [comment]
@mmellin, give the following a shot in your cluster config yaml:

```
spec:
  global:
    featureGates:
      ServerSideApply: false
```

I believe this should work after looking at https://github.com/gravitational/planet/blob/6bbbe82c669d4d5edc60026aa267c8c66be15e0b/tool/planet/start.go#L540 and the docs linked in https://github.com/gravitational/gravity/issues/655#issuecomment-532270226.

Please reopen if the above doesn't work, or if you believe our docs could be improved to better explain how to use feature gates.
