### ISSUE TITLE
Exclude gravity packages/apps when disabled in Bundle

### ISSUE THREAD

**Issue by helgi** [gravitational/gravity#887]
Defining one of the following:
```
extensions:
  logs:
    disabled: true
  monitoring:
    disabled: true
  kubernetes:
    disabled: true
  catalog:
    disabled: true
```

It will disable installation and UI elements but `tele build` will still include all the relevant packages, i.e. the resulting tar file does not get any smaller.

Talked to @r0mant about this briefly so he has more context
